### ISSUE TITLE
TEAM Path Configuration not available after installation, and exits (not gracefully) when file is not available.

### ISSUE THREAD

**Issue by RoelantVos** [RoelantVos/TEAM#68]
Temporary solution is to run as admin, as files and directory need to be created by the tool. When the files are there, all is fine. Could also be done via install as workaround of not having to need admin.

**Comment by graemeport** [comment]
Another workaround is to install the product outside the Program Files folder, such as D:\TEAM.

**Comment by RoelantVos** [comment]
This is now fixed, as all main standard config files/paths are created by the installer. Also added some additional exception handling here and there.
