### ISSUE TITLE
Links for https://app.sqldbm.com don't work

### ISSUE THREAD

**Issue by LucianoBastian** [RoelantVos/TEAM#85]
https://app.sqldbm.com/SQLServer/Share/d_5ad8GB9XpDuBx5p5pFM0GFrngIE8md_DYjF4jNYw0

**Comment by RoelantVos** [comment]
This has been updated  on http://roelantvos.com/blog/team-sample-data/.

Unfortunately, SQLDBM disabled the link sharing feature. So back to exports and uploads.
